-- ==========================================
-- SCRIPT DE BASE DE DATOS PARA ORACLE 21c
-- ==========================================

-- Dropping tables (using PL/SQL block to ignore errors if they do not exist)
BEGIN
   FOR cur_rec IN (SELECT table_name FROM user_tables WHERE table_name IN (
       'NOTIFICACIONES', 'PAGOS', 'RESERVA', 'CONTRATO', 'TIPO_CONTRATO', 'HABITACIONES', 
       'CLIENTES', 'USUARIOS', 'PERMISOS_ROL_MODULO', 'MODULOS', 'ROLES'))
   LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || cur_rec.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
/

-- ==========================================
-- MÓDULO DE SEGURIDAD Y ACCESO (RBAC)
-- ==========================================

CREATE TABLE roles (
  id_rol NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR2(50) NOT NULL,
  descripcion VARCHAR2(150),
  estado CHAR(1) DEFAULT '1',
  PRIMARY KEY (id_rol),
  CONSTRAINT uq_rol_nombre UNIQUE (nombre)
);

CREATE TABLE modulos (
  id_modulo NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR2(50) NOT NULL,
  ruta VARCHAR2(100),
  icono VARCHAR2(50),
  orden NUMBER(10) DEFAULT 0,
  PRIMARY KEY (id_modulo)
);

CREATE TABLE permisos_rol_modulo (
  id_permiso NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
  ver_modulo NUMBER(1) DEFAULT 0,
  p_view NUMBER(1) DEFAULT 0,
  p_create NUMBER(1) DEFAULT 0,
  p_edit NUMBER(1) DEFAULT 0,
  p_delete NUMBER(1) DEFAULT 0,
  id_rol NUMBER(10) NOT NULL,
  id_modulo NUMBER(10) NOT NULL,
  PRIMARY KEY (id_permiso),
  CONSTRAINT fk_permiso_rol FOREIGN KEY (id_rol) REFERENCES roles (id_rol) ON DELETE CASCADE,
  CONSTRAINT fk_permiso_modulo FOREIGN KEY (id_modulo) REFERENCES modulos (id_modulo) ON DELETE CASCADE
);

CREATE TABLE usuarios (
  id_usuario NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
  email VARCHAR2(100) NOT NULL,
  contrasena VARCHAR2(255) NOT NULL,
  nombre VARCHAR2(100) NOT NULL,
  habilitado NUMBER(1) DEFAULT 1,
  id_rol NUMBER(10) NOT NULL,
  PRIMARY KEY (id_usuario),
  CONSTRAINT uq_usuario_email UNIQUE (email),
  CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol) REFERENCES roles (id_rol)
);

CREATE TABLE notificaciones (
  id_notificacion NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
  tipo VARCHAR2(30) NOT NULL,
  mensaje VARCHAR2(255) NOT NULL,
  fecha_creacion DATE DEFAULT SYSDATE,
  leido NUMBER(1) DEFAULT 0,
  id_usuario NUMBER(10) NOT NULL,
  url_destino VARCHAR2(100),
  PRIMARY KEY (id_notificacion),
  CONSTRAINT fk_notif_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario) ON DELETE CASCADE
);

-- ==========================================
-- MÓDULO DE NEGOCIO (RESIDENCIA/ALQUILERES)
-- ==========================================

CREATE TABLE clientes (
  id_cliente NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR2(50) NOT NULL,
  ap_paterno VARCHAR2(50) NOT NULL,
  ap_materno VARCHAR2(50),
  nro_documento VARCHAR2(15) NOT NULL,
  telefono VARCHAR2(15),
  email VARCHAR2(100),
  fecha_nac DATE,
  PRIMARY KEY (id_cliente),
  CONSTRAINT uq_cliente_doc UNIQUE (nro_documento)
);

CREATE TABLE habitaciones (
  id_habitacion NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
  numero VARCHAR2(10) NOT NULL,
  tipo VARCHAR2(30) NOT NULL,
  precio NUMBER(10,2) NOT NULL,
  piso NUMBER(10),
  tipo_bano VARCHAR2(20) DEFAULT 'Propio',
  img_habitacion VARCHAR2(255),
  estado VARCHAR2(20) DEFAULT 'Disponible',
  PRIMARY KEY (id_habitacion),
  CONSTRAINT uq_habitacion_num UNIQUE (numero)
);

CREATE TABLE tipo_contrato (
  id_tipoContrato NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR2(30) NOT NULL,
  dias_duracion NUMBER(10) NOT NULL,
  estado CHAR(1) DEFAULT '1',
  PRIMARY KEY (id_tipoContrato),
  CONSTRAINT uq_tipocontrato_nombre UNIQUE (nombre)
);

CREATE TABLE contrato (
  id_contrato NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE,
  estado CHAR(1) DEFAULT '1',
  id_tipoContrato NUMBER(10) NOT NULL,
  id_cliente NUMBER(10) NOT NULL,
  id_habitacion NUMBER(10) NOT NULL,
  id_usuario NUMBER(10) NOT NULL,
  PRIMARY KEY (id_contrato),
  CONSTRAINT fk_contrato_tipo FOREIGN KEY (id_tipoContrato) REFERENCES tipo_contrato (id_tipoContrato),
  CONSTRAINT fk_contrato_cliente FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente),
  CONSTRAINT fk_contrato_habitacion FOREIGN KEY (id_habitacion) REFERENCES habitaciones (id_habitacion),
  CONSTRAINT fk_contrato_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario)
);

CREATE TABLE reserva (
  id_reserva NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
  fecha_reserva DATE NOT NULL,
  fecha_posibleIni DATE,
  estado CHAR(1) DEFAULT '1',
  id_cliente NUMBER(10) NOT NULL,
  id_habitacion NUMBER(10) NOT NULL,
  id_usuario NUMBER(10),
  PRIMARY KEY (id_reserva),
  CONSTRAINT fk_reserva_cliente FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente),
  CONSTRAINT fk_reserva_habitacion FOREIGN KEY (id_habitacion) REFERENCES habitaciones (id_habitacion),
  CONSTRAINT fk_reserva_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario)
);

CREATE TABLE pagos (
  id_pago NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
  monto NUMBER(10,2) NOT NULL,
  fecha DATE NOT NULL,
  metodo_pago VARCHAR2(50),
  concepto VARCHAR2(100),
  img_comprobante VARCHAR2(255),
  estado CHAR(1) DEFAULT '1',
  id_reserva NUMBER(10) DEFAULT NULL,
  id_contrato NUMBER(10) DEFAULT NULL,
  id_usuario NUMBER(10) NOT NULL,
  PRIMARY KEY (id_pago),
  CONSTRAINT fk_pago_reserva FOREIGN KEY (id_reserva) REFERENCES reserva (id_reserva),
  CONSTRAINT fk_pago_contrato FOREIGN KEY (id_contrato) REFERENCES contrato (id_contrato),
  CONSTRAINT fk_pago_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario)
);

-- ==========================================
-- INSERCIÓN DE DATOS BÁSICOS PARA PRUEBAS
-- ==========================================

-- Roles del sistema
INSERT INTO roles (nombre, descripcion) VALUES ('ADMIN', 'Administrador total del sistema');
INSERT INTO roles (nombre, descripcion) VALUES ('GERENTE', 'Gerente con acceso a reportes y dashboard');
INSERT INTO roles (nombre, descripcion) VALUES ('ESTUDIANTE', 'Inquilino/Estudiante con acceso a su propia información');

-- Usuarios de prueba (contraseña: admin123 en SHA-256)
INSERT INTO usuarios (email, contrasena, nombre, habilitado, id_rol) 
VALUES ('Sarai@gmail.com', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Sarai', 1, 1);

INSERT INTO usuarios (email, contrasena, nombre, habilitado, id_rol) 
VALUES ('gerente@residencia.com', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Jorge A. T. Chavez', 1, 2);

-- Tipos de contrato
INSERT INTO tipo_contrato (nombre, dias_duracion) VALUES ('Quincenal', 15);
INSERT INTO tipo_contrato (nombre, dias_duracion) VALUES ('Mensual', 30);
INSERT INTO tipo_contrato (nombre, dias_duracion) VALUES ('Semestral', 180);
INSERT INTO tipo_contrato (nombre, dias_duracion) VALUES ('Anual', 365);

-- Módulos del sistema (la ruta debe coincidir con la URL del filtro)
INSERT INTO modulos (nombre, ruta, icono, orden) VALUES ('Dashboard', '/dashboard.html', 'fa-border-all', 0);
INSERT INTO modulos (nombre, ruta, icono, orden) VALUES ('Habitaciones', '/habitaciones.html', 'fa-bed', 1);
INSERT INTO modulos (nombre, ruta, icono, orden) VALUES ('Contratos', '/contratos.html', 'fa-file-signature', 2);
INSERT INTO modulos (nombre, ruta, icono, orden) VALUES ('Pagos', '/pagos.html', 'fa-money-bill', 3);
INSERT INTO modulos (nombre, ruta, icono, orden) VALUES ('Seguridad', '/seguridad.html', 'fa-shield-halved', 4);

-- Permisos completos para ADMIN (id_rol=1) en todos los módulos
INSERT INTO permisos_rol_modulo (ver_modulo, p_view, p_create, p_edit, p_delete, id_rol, id_modulo) VALUES (1, 1, 1, 1, 1, 1, 1);
INSERT INTO permisos_rol_modulo (ver_modulo, p_view, p_create, p_edit, p_delete, id_rol, id_modulo) VALUES (1, 1, 1, 1, 1, 1, 2);
INSERT INTO permisos_rol_modulo (ver_modulo, p_view, p_create, p_edit, p_delete, id_rol, id_modulo) VALUES (1, 1, 1, 1, 1, 1, 3);
INSERT INTO permisos_rol_modulo (ver_modulo, p_view, p_create, p_edit, p_delete, id_rol, id_modulo) VALUES (1, 1, 1, 1, 1, 1, 4);
INSERT INTO permisos_rol_modulo (ver_modulo, p_view, p_create, p_edit, p_delete, id_rol, id_modulo) VALUES (1, 1, 1, 1, 1, 1, 5);

-- Permisos para GERENTE (id_rol=2): solo Dashboard
INSERT INTO permisos_rol_modulo (ver_modulo, p_view, p_create, p_edit, p_delete, id_rol, id_modulo) VALUES (1, 1, 0, 0, 0, 2, 1);

COMMIT;

-- --------------------------------------------------------
-- NUEVAS TABLAS: INCIDENCIAS (MANTENIMIENTO) Y ALERTAS
-- --------------------------------------------------------

-- Tabla de Incidencias (Mantenimiento)
CREATE TABLE incidencias (
  id_incidencia NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_falla VARCHAR2(50) NOT NULL,
  descripcion VARCHAR2(500) NOT NULL,
  foto VARCHAR2(255),
  fecha_reporte TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  fecha_resolucion TIMESTAMP,
  estado VARCHAR2(20) DEFAULT 'Pendiente' NOT NULL,
  id_habitacion NUMBER NOT NULL,
  id_usuario NUMBER NOT NULL,
  CONSTRAINT fk_incid_hab FOREIGN KEY (id_habitacion) REFERENCES habitaciones(id_habitacion),
  CONSTRAINT fk_incid_usu FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);

-- Tabla de Alertas Automáticas
CREATE TABLE alertas (
  id_alerta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_alerta VARCHAR2(50) NOT NULL,
  mensaje VARCHAR2(500) NOT NULL,
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  leida CHAR(1) DEFAULT '0' NOT NULL,
  id_usuario NUMBER NOT NULL,
  CONSTRAINT fk_alerta_usu FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);

COMMIT;
